name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Start Application
        run: npm run print

      - name: Get Secrets from RevBits PAM
        id: get-secrets
        uses: revbits-github-actions
        with:
          pam_hostname: ${{ secrets.PAM_HOSTNAME }}
          api_key: ${{ secrets.API_KEY }}
          pam_secret_keys: ${{ secrets.SECRET_KEYS }}

      - name: Display Secrets
        run: |
          echo "Hostname: ${{ steps.get-secrets.outputs.pam_hostname }}"
          echo "API Key: ${{ steps.get-secrets.outputs.api_key }}"
          echo "Secret Keys: ${{ steps.get-secrets.outputs.pam_secret_keys }}"
